
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI Testing

on: [push, pull_request]

defaults:
  run:
    working-directory: server


jobs:
  build:

    runs-on: ubuntu-latest
      
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Crea variables .env
      run: |
        touch .env
        echo MONGODB_URL= ${{secrets.MONGODB_URL}} >> .env
        echo JWT_SECRET= ${{secrets.JWT_SECRET}} >> .env
        echo JWT_TIMEOUT_DURATION= ${{secrets.JWT_TIMEOUT_DURATION}} >> .env
        echo EMAIL_SMTP_HOST= ${{secrets.EMAIL_SMTP_HOST}} >> .env
        echo EMAIL_SMTP_PORT= ${{secrets.EMAIL_SMTP_PORT}} >> .env
        echo EMAIL_SMTP_USERNAME= ${{secrets.EMAIL_SMTP_USERNAME}} >> .env
        echo EMAIL_SMTP_PASSWORD= ${{secrets.EMAIL_SMTP_PASSWORD}} >> .env
        echo EMAIL_SMTP_SECURE= ${{secrets.EMAIL_SMTP_SECURE}} >> .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }} 
    - run: npm ci
    - run: npm test 
